title: Podcast title
email: contact@example.com
description: "Podcast description"
category: "Example"
keywords: "42, foo, bar"
podcast_start: "Sat, 17 Jun 2023 13:00:00 +1000"
explicit: "no"

permalink: /:title
exclude:
  - "LICENSE"
  - "Gemfile"
  - "Gemfile.lock"
  - "Makefile"
  - "downloaded.txt"
  - "CNAME"
  - "temp"
include:
  - "_*.mp3"
